### ISSUE TITLE
Warning - `NARGCHK` Usage in MATLAB R2016a - SEM_calc

### ISSUE THREAD

**Issue by RoyiAvital** [raacampbell/notBoxPlot#1]
It seems the function [`nargchk`](http://www.mathworks.com/help/matlab/ref/nargchk.html) will be removed in a future version of MATLAB.
Hence it creates a warning.

I think you better solve it so the usage of this function won't yield a warning.

Great function, really enjoying it.

Thank You.

**Comment by raacampbell** [comment]
done 09b1da90e5643ace9326b0f91e0a54927891ec35

**Comment by RoyiAvital** [comment]
Great.
Though there is no new release.

It's better to have releases so users can know when to update (Better have them with Release Notes, etc...).

**Comment by raacampbell** [comment]
I generally only do that for major changes, otherwise I'd be making a new release for each commit. The easiest way to stay up to date is to clone the repository with your favourite Git client. Then new commits will show up automatically. If you don't want to do that, then the date of the last commit is shown near the top of the main project page; so you always know exactly when the last commit was made.

**Comment by RoyiAvital** [comment]
Hi,
The last release was almost a year ago.
I agree not each commit should create a new version but maybe once in 3 months even if only small commits were made?

Thank You.
