### ISSUE TITLE
Display Only Outliers

### ISSUE THREAD

**Issue by RoyiAvital** [raacampbell/notBoxPlot#4]
Currently [`notBoxPlot()`](https://github.com/raacampbell/notBoxPlot) displays all samples.

Could a flag be added such that only samples which are outside the interval are displayed?

**Comment by raacampbell** [comment]
Maybe there is use for that which I haven't thought of, but my gut instinct is that this goes against the point of the plot. 

My motivation for making the function was to provide a way to show the "warts and all" distribution of the data along with the 95% confidence interval for the mean. The idea being that the plot can then sit alongside parametric statistical tests, such as t-tests and ANOVA. 

Is there something I'm missing? You can, of course, always remove points post-hoc via the handles.

**Comment by RoyiAvital** [comment]
Hi,
I had an issue when dealing with many many points per group.
Hence I'd prefer the choice to only see "Outliers" and have the Median + Mean + Std + Confidence Interval to represent the majority of the points.

**Comment by raacampbell** [comment]
I feel the problem with removing everything but the outliers is that you're no longer left with a clear impression of what the distribution really looks like. 

If you have so very many that this plot style doesn't work then I'd suggest a violin plot instead, since that preserves the distribution. This is prettiest implementation I've seen for MATLAB: https://github.com/bastibe/Violinplot-Matlab I think that's better than deciding, perhaps arbitrarily, what constitutes an outlier. Another option, should you not like the violin plot, would be to randomly remove a certain proportion of the data points from the notBoxPlot.

**Comment by RoyiAvital** [comment]
Yet, when the data is large and there are so many points you can not see the distribution even if you show all data points.

Think of the example you try to find features which discriminant between data, having the median, SD and Confidence Interval (And outliers) would be enough and great.

Hence I think the best would be letting the user decide.

Thank You.

P. S.
Having option to "Sub Sample" the data is also great, yet that can be done by the user before hand.

**Comment by raacampbell** [comment]
> Yet, when the data is large and there are so many points you can not see the distribution even if you show all data points.
> 
> Think of the example you try to find features which discriminant between data, having the median, SD and Confidence Interval (And outliers) would be enough and great.

I think the answer is to always show all of the distribution in as much detail as is reasonable. That generally means histograms and violin plots for larger sample sizes or some kind of scatter plot, as notBoxPlot does, for small to medium sample sizes (although histograms are also fine here too in most cases).

Once you start making likely arbitrary decisions as to what constitutes an outlier and overlaying only those, then you're just hiding data for no valid reason. There is _always_ a type of plot available that will show the whole distribution, so why not use it? Hiding data is against the ethos of notBoxPlot, which is why I'm not going to implement this. Sorry :)
